### PR TITLE
Add exercism.io

### PR DESCRIPTION
**Pull request by radavis**

### CODE REVIEW

**Comment by lostdesign** [comment]
Thanks, I guess in order to push to store, we'll merge this after the switch. @S3B4S what do you say?

**Comment by S3B4S** [comment]
Yeah, we should round up #91 and then add this (perhaps manually)

**Comment by lostdesign** [comment]
@radavis #91 was merged, can you resolve the conflict?

**Comment by lostdesign** [comment]
Can you please reopen the PR to `dev`? Didn't see it was into master.

**Pull request closed without merging**
