### PR TITLE
[WIP] Dynamic routing

### PR DESCRIPTION
**Pull request by S3B4S**
Just starting a PR as to check the preview deployment of netlify

### CODE REVIEW

**Comment by S3B4S** [comment]
It indeed does break when reloading the page, unfortunate that this only happens in prod (locally with `npm run dev` and running with docker both work fine).

**Comment by lostdesign** [comment]
Iwill create https://dev.webgems.io to have a prod testing :D

**Comment by S3B4S** [comment]
Cool, for now I could change the setup to keep seperate directories (as to generate the pages) but each page uses the same component which does the filtering based on `store.json`. This is *far* from ideal, but still a slight improvement over the current situation and that way the data and screens are decoupled at least and we can maintain just `store.json`.

Have you considered to build a static site instead of SSR? That'd possibly make this even easier, that way we can build static .html files for each resource page, comparable to `generatePage` of Gatsby https://www.gatsbyjs.org/docs/node-apis/#createPages.

**Comment by S3B4S** [comment]
Closing in favour of #69

**Pull request closed without merging**
