### PR TITLE
add new resources

### LINKED ISSUE #105: Add https://cantunsee.space to Design category
**Name**
Can't Unsee

**Description**
A game where your attention to details earns you a lot of coins. WARNING: Once you see the difference between the images, you won't be able to unsee it

**URL**
https://cantunsee.space

**Category**
design

### LINKED ISSUE #113: Add https://bennettfeely.com/clippy/ to CSS catagory
**Name**
Bennett Feely clip-path maker

**Description**
This CSS clip-path maker helped me understand the property and all the cool things you can do with it.

**URL**
https://bennettfeely.com/clippy/

**Category**
CSS

### LINKED ISSUE #128: Add image-color.com to design category
**Name**
Image Color Picker

**Description**
Image color picker and palette generator

**URL**
https://image-color.com

**Category**
Design

### PR DESCRIPTION
**Pull request by laurenoutloud**
fixes #128, fixes #113, fixes #105

### CODE REVIEW

**Comment by laurenoutloud** [comment]
added empty tags array to new resources

**Comment by lostdesign** [comment]
Btw, PRs will only be merged into dev. We will highlight that in the readme soon.

**Comment by laurenoutloud** [comment]
I'm working on taking out the package-lock.json. Tried to just delete it but not sure it had the desired outcome :P

**Comment by laurenoutloud** [comment]
Good to know, I changed the base branch from master to dev!

**Comment by lostdesign** [comment]
Well you literally deleted it. you need to remove the file from the commit.

**Comment by laurenoutloud** [comment]
Can you explain how to do that?

**Comment by S3B4S** [comment]
Hi, it's unfortunately not really that straight forwarded to remove the tracking of a file in a commit, I think the thing to do here is to reset your branch before you made this [commit](https://github.com/webgems/webgems/pull/140/commits/df456d060e6474b1528c2d8a865af05513b9d6c3).
There's an SO thread that explains how to go on about this: <https://stackoverflow.com/questions/12481639/remove-files-from-git-commit>


There's an easier way if it would be the most recent commit, but that's not the case now, just dropping it here anyway for future reference: https://help.github.com/en/articles/removing-files-from-a-repositorys-history

**Comment by laurenoutloud** [comment]
Well, that was fun :P 

Thanks for the info @S3B4S ! I went ahead and reverted to the first commit I made and overwrote all the changes

**Comment by S3B4S** [comment]
Great, thank you! 😄

**Pull request merged**
