### PR TITLE
Feature: Table/Card View Switch

### PR DESCRIPTION
**Pull request by karnthis**
Not yet ready for merge
Addresses #45 

Base switch between Card and Table modes. Currently controlled by basic checkbox on Sidenav, beautification to follow. 

Added:
- Components:
  - TableHead
  - TableRow
- `if` clause to determine which option shows
- Vuex store to share desired setting between routes

Changed:
- SideBar.vue now imports swap function and swap value from store

Todo:
[x] Beautification
[] Persistence between sessions
[] Version update
[] Readme update
[] Feedback rework

### CODE REVIEW

**Comment by karnthis** [comment]
Feature ready for review. Currently toggle selection is only persisted during the session, additional research required.

**Comment by S3B4S** [comment]
For the major part this looks good, thanks 😄 

One thing I'm concerned about is the repetition of certain logic, for example the functions `createCopyUrl` / `createReferenceTag` / `checkReference`.
To solve this I propose that we split the logic/view components. So, we'd have a component like

```js
// Pseudocode
<template lang="pug">
	<Cards v-if="cardsShown" :info="info">
	<Table v-else :info="info">
</template>

<script>
export default {
  data() { ... },
  methods: {
    async createCopyUrl() { ... },
    createReferenceTag(tag) { ... },
    checkReference() { ... }
  },
  mounted() { ... },
  watch: { ... }
};
</script>
```

And the Cards & Table components would receive the data as props, and in those components we only care about the styling of the Cards/Table itself.

**Comment by karnthis** [comment]
So keeping the Active highlight functioning post-split turned into a major headache, but I did manage to keep in. I think the latest commit is a pretty good implementation of what S3B4S was referring to, but I am open to feedback.

The new layout also meant I could combine the multiple functions into a single one with less redundant code.

**Comment by S3B4S** [comment]
Ah thanks for implementing my suggestion 😄 

I'm curious about [this part](https://github.com/webgems/webgems/pull/111/files#diff-0ffec70fccc0dcd1e4ba051e39b3e5d5R11-R47) though, if I'm following along correctly, this part is unnecessary for the header and could be safely removed (tried this out locally).

I'd also like to see the `createCopyUrl` in 1 place that will be shared across both the Table and Cards view (since if the copy url has to be changed for Table, it will need to be changed aswell for Card). It could be implemented in `_category.vue` and passed as a prop.

I'm fine with implementing these changes, but I wanted to double check I'm following along correctly, let me know. :)

Once again, thanks, I'm happy to see the alternative view being implemented along with the highlight.

**Comment by S3B4S** [comment]
@lostdesign I'd appreciate if you could take a look at the UI and let us know what you think, this is getting close to being able to be merged codewise :)

**Comment by karnthis** [comment]
@S3B4S I have not been able to find a way to pass around a function, and would love to know a good way to do it. What is your suggestion? 
...Unless I am totally misunderstanding you, and the prop would only be passing the URL/other data down while the function would live locally?

As for the header, that was just me forgetting the logic was even in there. I'll clean that up now.

**Comment by S3B4S** [comment]
Just made a commit that showcases my suggestion, basically passing down a function body to use as a callback in the children components. Had to make some slight modifications to make this work off course. Can you please let me know if this all still works as intended? :)

**Comment by karnthis** [comment]
That is very interesting, I have not seen passing a function reference to a prop before. I have not had a chance to test it, but I will take your word for it that it works.

**Pull request merged**
