### PR TITLE
Feature: Resource Auto-sort

### PR DESCRIPTION
**Pull request by karnthis**
Addresses #70 with an auto alphabetical sort. Can be modified to support of sorting critera as well.

### CODE REVIEW

**Comment by lostdesign** [comment]
Mhh it seems like it's from a former PR, probs the card/table switcher.

**Comment by karnthis** [comment]
I’ll look into it, but I would be surprised if the switch is the cause. It didn’t touch the styling for cards

**Comment by karnthis** [comment]
It displays fine on my device:
https://i.imgur.com/cP8FK7V.png
1920x1080 resolution, firefox.

https://i.imgur.com/vABYzIb.png
Break points appear to be working, could you please provide more details?

**Comment by S3B4S** [comment]
The issue seems to be that the boxes don't autofill the height, take a look here to see what I mean: https://webgems.io/css

**Comment by karnthis** [comment]
Looks like I introduced an extra div by mistake. that has been corrected with this latest push.

**Pull request merged**
