### PR TITLE
add fade transitions per page, hover effect

### PR DESCRIPTION
**Pull request by jpoechill**
What does this PR do?

1) Adds a simple mouse hover (tint) effect on each of the cards
2) Adds a fade transition effect for each page/route change

Are these changes necessary?

These changes are _not_ completely necessary and life could be lived without them. :)

Why should these changes be merge?

These changes are not dire by any means, and merely provide for a more _enhanced_ user experience. While there is a feeling that the site attempts to come off as hyper progressive in design/simplicity, there are some minor details lacking that complete this.

The purpose of these changes would be to invite users to more explore and interact with page elements.

xx

### CODE REVIEW

**Comment by jpoechill** [comment]
done. cheers

**Comment by lostdesign** [comment]
Please change branch to dev and resolve the conflict.

**Comment by lostdesign** [comment]
@jpoechill Sorry for the inconvenience, could you revert to your first commit? We'd like to merge that one, now that we saw you're actually using the config page transitions.

**Comment by lostdesign** [comment]
Will reopen once adjusted.

**Pull request closed without merging**
